version: '3.8'

services:
  keycloakdb:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      PGPORT: ${KEYCLOAK_DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports: 
      - 5438:${KEYCLOAK_DB_PORT}
    volumes:
      - ./keycloak/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./keycloak/db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    depends_on:
      keycloakdb:
        condition: service_healthy
    environment:
      KC_DB: ${KEYCLOAK_DB_NAME}
      KC_DB_URL: jdbc:postgresql://keycloakdb:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    restart: always
    ports:
      - ${KEYCLOAK_PORT}:8080
    entrypoint: /opt/keycloak/bin/kc.sh start-dev

  appdb:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      PGPORT: ${APP_DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${APP_DB_PORT_EXPOSED}:${APP_DB_PORT}
    volumes:
      - ./app/db:/var/lib/postgresql/data

  appfront:
    image: node:lts
    restart: on-failure
    working_dir: /root/app
    ports:
      - ${APP_FRONT_PORT}:${APP_FRONT_PORT}
    volumes:
      - ./app/front:/root/app
    command: sh -c "npm install && npx playwright install --with-deps && npm run dev"

  appback:
    image: maven:latest
    restart: on-failure
    working_dir: /root/app
    ports:
      - ${APP_BACK_PORT}:${APP_BACK_PORT}
    volumes:
      - ./app/back:/root/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://appdb:${APP_DB_PORT}/${APP_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${APP_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${APP_DB_PASSWORD}
    command: sh -c " mvn clean compile exec:java -Dexec.mainClass=fr.gouv.monprojetsup.MonProjetSupApplication"
