name: App Frontend - Tests and Linters

on:
  push:
    branches:
      - main
  pull_request:

env:
  WORKING_DIRECTORY: ./app/front

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install npm packages
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci

  test:
    name: Run tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages

      - name: Run test command
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run test

  lint:
    name: Run linters for code
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages

      - name: Run lint command
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run lint
  
  playwright:
    name: Run Playwright tests
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages

      - name: Install Playwright
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npx playwright install --with-deps chromium

      - name: Copy .env
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cp .env.ci .env

      - name: Run Playwright tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npx playwright test